name: Continuous Integration

on: [push]

jobs:
  # Uses: https://github.com/haskell/actions/tree/main/setup
  test:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4.7'
          cabal-version: '3.8' # Exact version of Cabal

      # Reference: https://github.com/actions/cache/blob/main/examples.md#haskell---stack
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-notes
          restore-keys: |
            ${{ runner.os }}-stack-global-

      - uses: actions/cache@v3
        name: Cache RTFParser .stack-work
        with:
          path: ./RTFParser/.stack-work
          key: ${{ runner.os }}-stack-work-notes
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: ./.stack-work
          key: ${{ runner.os }}-stack-work-notes
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - name: Test RTF Parser
        working-directory: ./RTFParser
        run: make test

      - name: Test Notes
        run: make test

